baseURL: "https://tanmay-bhat.github.io"
title: Tanmay Bhat
pagination:
  pagerSize: 5
theme: PaperMod

enableInlineShortcodes: true
enableEmoji: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: G-6PXF78BGMY

disqusShortname: tanmaybhat

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Tanmay Bhat
  description: "DevOps || Cloud Engineer based in Banglore."
  keywords: [Blog, Portfolio]
  author: Tanmay Bhat
  # author: ["Me", "You"] # multiple authors
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # auto, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: true
  hidemeta: false
  hideSummary: true
  showtoc: false
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "memoji.png"
    # favicon16x16: "<link / abs url>"
    # favicon32x32: "<link / abs url>"
    # apple_touch_icon: "<link / abs url>"
    # safari_pinned_tab: "<link / abs url>"

  label:
    text: "Home"
    # icon: /apple-touch-icon.png
    # iconHeight: 35

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: Tanmay Bhat
    subtitle: "SRE || DevOps Engineer"
    imageUrl: "tanmay-memoji.jpeg"
    imageWidth: 250
    imageHeight: 250
    imageTitle: tanmay_welcome_memoji
    # buttons:
    #   - name: About
    #     url: about
    #   - name: Posts
    #     url: posts
    #   - name: Tags
    #     url: tags

  # home-info mode
  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: Welcome to my blog

  socialIcons:
    - name: twitter
      url: "https://twitter.com/Tanmaybhat98"
    # - name: stackoverflow
    #   url: "https://stackoverflow.com"
    - name: email
      url: "mailto:tanmaybhat24@gmail.com"
    - name: github
      url: "https://github.com/tanmay-bhat/"
    - name: linkedin
      url: "https://www.linkedin.com/in/tanmay-bhat-024/"
    - name: KoFi
      url: "https://ko-fi.com/tanmaybhat"

  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    URL: "https://github.com/tanmay-bhat/tanmay-bhat.github.io/blob/main/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: about
      name: About
      url: /about/
      weight: 10
    - identifier: posts
      name: Posts
      url: /posts/
      weight: 20
    # - identifier: tags
    #   name: Tags
    #   url: /tags/
    #   weight: 30
    - identifier: search
      name: Search
      url: /search/
      weight: 40
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
# markup:
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         style: monokai

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary
